move_list = [
    "Pound",
    "Karate Chop",
    "Double Slap",
    "Comet Punch",
    "Mega Punch",
    "Pay Day",
    "Fire Punch",
    "Ice Punch",
    "Thunder Punch",
    "Scratch",
    "Vise Grip",
    "Guillotine",
    "Razor Wind",
    "Cut",
    "Gust",
    "Wing Attack",
    "Fly",
    "Bind",
    "Slam",
    "Vine Whip",
    "Stomp",
    "Double Kick",
    "Mega Kick",
    "Jump Kick",
    "Rolling Kick",
    "Headbutt",
    "Horn Attack",
    "Fury Attack",
    "Horn Drill",
    "Tackle",
    "Body Slam",
    "Wrap",
    "Take Down",
    "Thrash",
    "Double-Edge",
    "Poison Sting",
    "Twineedle",
    "Pin Missile",
    "Bite",
    "Sonic Boom",
    "Acid",
    "Ember",
    "Flamethrower",
    "Water Gun",
    "Hydro Pump",
    "Surf",
    "Ice Beam",
    "Blizzard",
    "Psybeam",
    "Bubble Beam",
    "Aurora Beam",
    "Hyper Beam",
    "Peck",
    "Drill Peck",
    "Submission",
    "Low Kick",
    "Counter",
    "Seismic Toss",
    "Strength",
    "Absorb",
    "Mega Drain",
    "Razor Leaf",
    "Solar Beam",
    "Petal Dance",
    "Dragon Rage",
    "Fire Spin",
    "Thunder Shock",
    "Thunderbolt",
    "Thunder",
    "Rock Throw",
    "Earthquake",
    "Fissure",
    "Dig",
    "Confusion",
    "Psychic",
    "Quick Attack",
    "Rage",
    "Night Shade",
    "Bide",
    "Self-Destruct",
    "Egg Bomb",
    "Lick",
    "Smog",
    "Sludge",
    "Bone Club",
    "Fire Blast",
    "Waterfall",
    "Clamp",
    "Swift",
    "Skull Bash",
    "Spike Cannon",
    "Constrict",
    "High Jump Kick",
    "Dream Eater",
    "Barrage",
    "Leech Life",
    "Sky Attack",
    "Bubble",
    "Dizzy Punch",
    "Psywave",
    "Crabhammer",
    "Explosion",
    "Fury Swipes",
    "Bonemerang",
    "Rock Slide",
    "Hyper Fang",
    "Tri Attack",
    "Super Fang",
    "Slash",
    "Triple Kick",
    "Thief",
    "Flame Wheel",
    "Snore",
    "Flail",
    "Aeroblast",
    "Reversal",
    "Powder Snow",
    "Mach Punch",
    "Feint Attack",
    "Sludge Bomb",
    "Mud-Slap",
    "Octazooka",
    "Zap Cannon",
    "Icy Wind",
    "Bone Rush",
    "Outrage",
    "Giga Drain",
    "Rollout",
    "False Swipe",
    "Spark",
    "Fury Cutter",
    "Steel Wing",
    "Return",
    "Present",
    "Frustration",
    "Sacred Fire",
    "Magnitude",
    "Dynamic Punch",
    "Megahorn",
    "Dragon Breath",
    "Pursuit",
    "Rapid Spin",
    "Iron Tail",
    "Metal Claw",
    "Vital Throw",
    "Hidden Power",
    "Cross Chop",
    "Twister",
    "Crunch",
    "Mirror Coat",
    "Extreme Speed",
    "Ancient Power",
    "Shadow Ball",
    "Future Sight",
    "Rock Smash",
    "Whirlpool",
    "Beat Up",
    "Fake Out",
    "Uproar",
    "Spit Up",
    "Heat Wave",
    "Facade",
    "Focus Punch",
    "Smelling Salts",
    "Superpower",
    "Revenge",
    "Brick Break",
    "Knock Off",
    "Endeavor",
    "Eruption",
    "Secret Power",
    "Dive",
    "Arm Thrust",
    "Luster Purge",
    "Mist Ball",
    "Blaze Kick",
    "Ice Ball",
    "Needle Arm",
    "Hyper Voice",
    "Poison Fang",
    "Crush Claw",
    "Blast Burn",
    "Hydro Cannon",
    "Meteor Mash",
    "Astonish",
    "Weather Ball",
    "Air Cutter",
    "Overheat",
    "Rock Tomb",
    "Silver Wind",
    "Water Spout",
    "Signal Beam",
    "Shadow Punch",
    "Extrasensory",
    "Sky Uppercut",
    "Sand Tomb",
    "Sheer Cold",
    "Muddy Water",
    "Bullet Seed",
    "Aerial Ace",
    "Icicle Spear",
    "Dragon Claw",
    "Frenzy Plant",
    "Bounce",
    "Mud Shot",
    "Poison Tail",
    "Covet",
    "Volt Tackle",
    "Magical Leaf",
    "Leaf Blade",
    "Rock Blast",
    "Shock Wave",
    "Water Pulse",
    "Doom Desire",
    "Psycho Boost",
    "Wake-Up Slap",
    "Hammer Arm",
    "Gyro Ball",
    "Brine",
    "Natural Gift",
    "Feint",
    "Pluck",
    "Metal Burst",
    "U-turn",
    "Close Combat",
    "Payback",
    "Assurance",
    "Fling",
    "Trump Card",
    "Wring Out",
    "Punishment",
    "Last Resort",
    "Sucker Punch",
    "Flare Blitz",
    "Force Palm",
    "Aura Sphere",
    "Poison Jab",
    "Dark Pulse",
    "Night Slash",
    "Aqua Tail",
    "Seed Bomb",
    "Air Slash",
    "X-Scissor",
    "Bug Buzz",
    "Dragon Pulse",
    "Dragon Rush",
    "Power Gem",
    "Drain Punch",
    "Vacuum Wave",
    "Focus Blast",
    "Energy Ball",
    "Brave Bird",
    "Earth Power",
    "Giga Impact",
    "Bullet Punch",
    "Avalanche",
    "Ice Shard",
    "Shadow Claw",
    "Thunder Fang",
    "Ice Fang",
    "Fire Fang",
    "Shadow Sneak",
    "Mud Bomb",
    "Psycho Cut",
    "Zen Headbutt",
    "Mirror Shot",
    "Flash Cannon",
    "Rock Climb",
    "Draco Meteor",
    "Discharge",
    "Lava Plume",
    "Leaf Storm",
    "Power Whip",
    "Rock Wrecker",
    "Cross Poison",
    "Gunk Shot",
    "Iron Head",
    "Magnet Bomb",
    "Stone Edge",
    "Grass Knot",
    "Chatter",
    "Judgment",
    "Bug Bite",
    "Charge Beam",
    "Wood Hammer",
    "Aqua Jet",
    "Attack Order",
    "Head Smash",
    "Double Hit",
    "Roar of Time",
    "Spacial Rend",
    "Crush Grip",
    "Magma Storm",
    "Seed Flare",
    "Ominous Wind",
    "Shadow Force",
    "Psyshock",
    "Venoshock",
    "Smack Down",
    "Storm Throw",
    "Flame Burst",
    "Sludge Wave",
    "Heavy Slam",
    "Synchronoise",
    "Electro Ball",
    "Flame Charge",
    "Low Sweep",
    "Acid Spray",
    "Foul Play",
    "Round",
    "Echoed Voice",
    "Chip Away",
    "Clear Smog",
    "Stored Power",
    "Scald",
    "Hex",
    "Sky Drop",
    "Circle Throw",
    "Incinerate",
    "Acrobatics",
    "Retaliate",
    "Final Gambit",
    "Inferno",
    "Water Pledge",
    "Fire Pledge",
    "Grass Pledge",
    "Volt Switch",
    "Struggle Bug",
    "Bulldoze",
    "Frost Breath",
    "Dragon Tail",
    "Electroweb",
    "Wild Charge",
    "Drill Run",
    "Dual Chop",
    "Heart Stamp",
    "Horn Leech",
    "Sacred Sword",
    "Razor Shell",
    "Heat Crash",
    "Leaf Tornado",
    "Steamroller",
    "Night Daze",
    "Psystrike",
    "Tail Slap",
    "Hurricane",
    "Head Charge",
    "Gear Grind",
    "Searing Shot",
    "Techno Blast",
    "Relic Song",
    "Secret Sword",
    "Glaciate",
    "Bolt Strike",
    "Blue Flare",
    "Fiery Dance",
    "Freeze Shock",
    "Ice Burn",
    "Snarl",
    "Icicle Crash",
    "V-create",
    "Fusion Flare",
    "Fusion Bolt",
    "Flying Press",
    "Belch",
    "Fell Stinger",
    "Phantom Force",
    "Parabolic Charge",
    "Petal Blizzard",
    "Freeze-Dry",
    "Disarming Voice",
    "Draining Kiss",
    "Play Rough",
    "Fairy Wind",
    "Moonblast",
    "Boomburst",
    "Diamond Storm",
    "Steam Eruption",
    "Hyperspace Hole",
    "Water Shuriken",
    "Mystical Fire",
    "Dazzling Gleam",
    "Nuzzle",
    "Infestation",
    "Power-Up Punch",
    "Oblivion Wing",
    "Thousand Arrows",
    "Thousand Waves",
    "Land’s Wrath",
    "Light of Ruin",
    "Origin Pulse",
    "Precipice Blades",
    "Dragon Ascent",
    "Hyperspace Fury",
    "First Impression",
    "Spirit Shackle",
    "Darkest Lariat",
    "Sparkling Aria",
    "Ice Hammer",
    "High Horsepower",
    "Solar Blade",
    "Leafage",
    "Throat Chop",
    "Pollen Puff",
    "Anchor Shot",
    "Lunge",
    "Fire Lash",
    "Power Trip",
    "Burn Up",
    "Smart Strike",
    "Revelation Dance",
    "Core Enforcer",
    "Trop Kick",
    "Beak Blast",
    "Clanging Scales",
    "Dragon Hammer",
    "Brutal Swing",
    "Shell Trap",
    "Fleur Cannon",
    "Psychic Fangs",
    "Stomping Tantrum",
    "Shadow Bone",
    "Accelerock",
    "Liquidation",
    "Prismatic Laser",
    "Spectral Thief",
    "Sunsteel Strike",
    "Moongeist Beam",
    "Zing Zap",
    "Nature’s Madness",
    "Multi-Attack",
    "Mind Blown",
    "Plasma Fists",
    "Photon Geyser",
    "Zippy Zap",
    "Splishy Splash",
    "Floaty Fall",
    "Bouncy Bubble",
    "Buzzy Buzz",
    "Sizzly Slide",
    "Glitzy Glow",
    "Baddy Bad",
    "Sappy Seed",
    "Freezy Frost",
    "Sparkly Swirl",
    "Double Iron Bash",
    "Dynamax Cannon",
    "Snipe Shot",
    "Jaw Lock",
    "Dragon Darts",
    "Bolt Beak",
    "Fishious Rend",
    "Body Press",
    "Drum Beating",
    "Snap Trap",
    "Pyro Ball",
    "Aura Wheel",
    "Breaking Swipe",
    "Branch Poke",
    "Overdrive",
    "Apple Acid",
    "Grav Apple",
    "Spirit Break",
    "Strange Steam",
    "False Surrender",
    "Meteor Assault",
    "Eternabeam",
    "Steel Beam",
    "Expanding Force",
    "Steel Roller",
    "Scale Shot",
    "Meteor Beam",
    "Shell Side Arm",
    "Misty Explosion",
    "Grassy Glide",
    "Rising Voltage",
    "Terrain Pulse",
    "Skitter Smack",
    "Burning Jealousy",
    "Lash Out",
    "Poltergeist",
    "Flip Turn",
    "Triple Axel",
    "Dual Wingbeat",
    "Scorching Sands",
    "Wicked Blow",
    "Surging Strikes",
    "Thunder Cage",
    "Dragon Energy",
    "Freezing Glare",
    "Fiery Wrath",
    "Thunderous Kick",
    "Glacial Lance",
    "Astral Barrage",
    "Eerie Spell",
    "Dire Claw",
    "Psyshield Bash",
    "Stone Axe",
    "Springtide Storm",
    "Mystical Power",
    "Raging Fury",
    "Wave Crash",
    "Chloroblast",
    "Mountain Gale",
    "Headlong Rush",
    "Barb Barrage",
    "Esper Wing",
    "Bitter Malice",
    "Triple Arrows",
    "Infernal Parade",
    "Ceaseless Edge",
    "Bleakwind Storm",
    "Wildbolt Storm",
    "Sandsear Storm",
    "Tera Blast",
    "Axe Kick",
    "Last Respects",
    "Lumina Crash",
    "Order Up",
    "Jet Punch",
    "Spin Out",
    "Population Bomb",
    "Ice Spinner",
    "Glaive Rush",
    "Salt Cure",
    "Triple Dive",
    "Mortal Spin",
    "Kowtow Cleave",
    "Flower Trick",
    "Torch Song",
    "Aqua Step",
    "Raging Bull",
    "Make It Rain",
    "Psyblade",
    "Hydro Steam",
    "Ruination",
    "Collision Course",
    "Electro Drift",
    "Pounce",
    "Trailblaze",
    "Chilling Water",
    "Hyper Drill",
    "Twin Beam",
    "Rage Fist",
    "Armor Cannon",
    "Bitter Blade",
    "Double Shock",
    "Gigaton Hammer",
    "Comeuppance",
    "Aqua Cutter"
]